### ISSUE TITLE
lmao

### ISSUE THREAD

**Issue by longles** [CSC207-UofT/course-project-mer#2]
very nice
![forks](https://user-images.githubusercontent.com/59178875/137638952-dd117bf9-d81a-435f-bfb0-68d32cb65cee.PNG)

**Comment by RuYi-NG** [comment]
> 
> 
> very nice ![forks](https://user-images.githubusercontent.com/59178875/137638952-dd117bf9-d81a-435f-bfb0-68d32cb65cee.PNG)

**_Forking for future entrepreneurship idea, definitely not something sus_** @warzone2243

**Comment by StewartChandler** [comment]
lamo

**Comment by StewartChandler** [comment]
lamo
